channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - scikit-learn
      - imbalanced-learn
      - geometric-smote
      - research-learn
      - git+https://github.com/NOVA-IMS-Innovation-and-Analytics-Lab/publications.git
